export default [
	{ label: 'Calo Duro em pé direito ', value: 'Calo Duro em pé direito ' },
	{ label: 'Calo Duro em Halux direito ', value: 'Calo Duro em Halux direito ' },
	{ label: 'Calo Duro em Arteiro 1 direito ', value: 'Calo Duro em Arteiro 1 direito ' },
	{ label: 'Calo Duro em Arteiro 2 direito ', value: 'Calo Duro em Arteiro 2 direito ' },
	{ label: 'Calo Duro em Arteiro 3 direito ', value: 'Calo Duro em Arteiro 3 direito ' },
	{ label: 'Calo Duro em Arteiro 4 direito ', value: 'Calo Duro em Arteiro 4 direito ' },
	{ label: 'Calo Duro em pé esquerdo ', value: 'Calo Duro em pé esquerdo ' },
	{ label: 'Calo Duro em Halux esquerdo ', value: 'Calo Duro em Halux esquerdo ' },
	{ label: 'Calo Duro em Arteiro 1 esquerdo ', value: 'Calo Duro em Arteiro 1 esquerdo ' },
	{ label: 'Calo Duro em Arteiro 2 esquerdo ', value: 'Calo Duro em Arteiro 2 esquerdo ' },
	{ label: 'Calo Duro em Arteiro 3 esquerdo ', value: 'Calo Duro em Arteiro 3 esquerdo ' },
	{ label: 'Calo Duro em Arteiro 4 esquerdo ', value: 'Calo Duro em Arteiro 4 esquerdo ' },
	{ label: 'Calo Interdigital em pé direito ', value: 'Calo Interdigital em pé direito ' },
	{ label: 'Calo Interdigital em Halux direito ', value: 'Calo Interdigital em Halux direito ' },
	{ label: 'Calo Interdigital em Arteiro 1 direito ', value: 'Calo Interdigital em Arteiro 1 direito ' },
	{ label: 'Calo Interdigital em Arteiro 2 direito ', value: 'Calo Interdigital em Arteiro 2 direito ' },
	{ label: 'Calo Interdigital em Arteiro 3 direito ', value: 'Calo Interdigital em Arteiro 3 direito ' },
	{ label: 'Calo Interdigital em Arteiro 4 direito ', value: 'Calo Interdigital em Arteiro 4 direito ' },
	{ label: 'Calo Interdigital em pé esquerdo ', value: 'Involuta em pé esquerdo ' },
	{ label: 'Calo Interdigital em Halux esquerdo ', value: 'Involuta em Halux esquerdo ' },
	{ label: 'Calo Interdigital em Arteiro 1 esquerdo ', value: 'Calo Interdigital em Arteiro 1 esquerdo ' },
	{ label: 'Calo Interdigital em Arteiro 2 esquerdo ', value: 'Calo Interdigital em Arteiro 2 esquerdo ' },
	{ label: 'Calo Interdigital em Arteiro 3 esquerdo ', value: 'Calo Interdigital em Arteiro 3 esquerdo ' },
	{ label: 'Calo Interdigital em Arteiro 4 esquerdo ', value: 'Calo Interdigital em Arteiro 4 esquerdo ' },
	{ label: 'Calo Plantar em pé direito ', value: 'Calo Plantar em pé direito ' },
	{ label: 'Calo Plantar em Halux direito ', value: 'Calo Plantar em Halux direito ' },
	{ label: 'Calo Plantar em Arteiro 1 direito ', value: 'Calo Plantar em Arteiro 1 direito ' },
	{ label: 'Calo Plantar em Arteiro 2 direito ', value: 'Calo Plantar em Arteiro 2 direito ' },
	{ label: 'Calo Plantar em Arteiro 3 direito ', value: 'Calo Plantar em Arteiro 3 direito ' },
	{ label: 'Calo Plantar em Arteiro 4 direito ', value: 'Calo Plantar em Arteiro 4 direito ' },
	{ label: 'Calo Plantar em pé esquerdo ', value: 'Calo Plantar em pé esquerdo ' },
	{ label: 'Calo Plantar em Halux esquerdo ', value: 'Calo Plantar em Halux esquerdo ' },
	{ label: 'Calo Plantar em Arteiro 1 esquerdo ', value: 'Calo Plantar em Arteiro 1 esquerdo' },
	{ label: 'Calo Plantar em Arteiro 2 esquerdo ', value: 'Calo Plantar em Arteiro 2 esquerdo' },
	{ label: 'Calo Plantar em Arteiro 3 esquerdo ', value: 'Calo Plantar em Arteiro 3 esquerdo' },
	{ label: 'Calo Plantar em Arteiro 4 esquerdo ', value: 'Calo Plantar em Arteiro 4 esquerdo' },
	{ label: 'Calo Dorsal em pé direito ', value: 'Calo Dorsal em pé direito  ' },
	{ label: 'Calo Dorsal em Halux direito ', value: 'Calo Dorsal em Halux direito  ' },
	{ label: 'Calo Dorsal em Arteiro 1 direito ', value: 'Calo Dorsal em Arteiro 1 direito' },
	{ label: 'Calo Dorsal em Arteiro 2 direito ', value: 'Calo Dorsal em Arteiro 2 direito' },
	{ label: 'Calo Dorsal em Arteiro 3 direito ', value: 'Calo Dorsal em Arteiro 3 direito' },
	{ label: 'Calo Dorsal em Arteiro 4 direito ', value: 'Calo Dorsal em Arteiro 4 direito' },
	{ label: 'Calo Dorsal em pé esquerdo ', value: 'Calo Dorsal em pé esquerdo ' },
	{ label: 'Calo Dorsal em Halux esquerdo ', value: 'Calo Dorsal em Halux esquerdo ' },
	{ label: 'Calo Dorsal em Arteiro 1 esquerdo ', value: 'Calo Dorsal em Arteiro 1 esquerdo ' },
	{ label: 'Calo Dorsal em Arteiro 2 esquerdo ', value: 'Calo Dorsal em Arteiro 2 esquerdo ' },
	{ label: 'Calo Dorsal em Arteiro 3 esquerdo ', value: 'Calo Dorsal em Arteiro 3 esquerdo ' },
	{ label: 'Calo Dorsal em Arteiro 4 esquerdo ', value: 'Calo Dorsal em Arteiro 4 esquerdo ' },
	{ label: 'Calo Miliar em pé direito ', value: 'Calo Miliar em pé direito ' },
	{ label: 'Calo Miliar em Halux direito ', value: 'Calo Miliar em Halux direito ' },
	{ label: 'Calo Miliar em Arteiro 1 direito ', value: 'Calo Miliar em Arteiro 1 direito ' },
	{ label: 'Calo Miliar em Arteiro 2 direito ', value: 'Calo Miliar em Arteiro 2 direito ' },
	{ label: 'Calo Miliar em Arteiro 3 direito ', value: 'Calo Miliar em Arteiro 3 direito ' },
	{ label: 'Calo Miliar em Arteiro 4 direito ', value: 'Calo Miliar em Arteiro 4 direito ' },
	{ label: 'Calo Miliar em pé esquerdo ', value: 'Calo Miliar em pé esquerdo' },
	{ label: 'Calo Miliar em Halux esquerdo ', value: 'Calo Miliar em Halux esquerdo' },
	{ label: 'Calo Miliar em Arteiro 1 esquerdo ', value: 'Calo Miliar em Arteiro 1 esquerdo ' },
	{ label: 'Calo Miliar em Arteiro 2 esquerdo ', value: 'Calo Miliar em Arteiro 2 esquerdo ' },
	{ label: 'Calo Miliar em Arteiro 3 esquerdo ', value: 'Calo Miliar em Arteiro 3 esquerdo ' },
	{ label: 'Calo Miliar em Arteiro 4 esquerdo ', value: 'Calo Miliar em Arteiro 4 esquerdo ' },
	{ label: 'Calo neurovascular em pé direito ', value: 'Calo neurovascular em pé direito ' },
	{ label: 'Calo neurovascular em Halux direito ', value: 'Calo neurovascular em Halux direito ' },
	{ label: 'Calo neurovascular em Arteiro 1 direito ', value: 'Calo neurovascular em Arteiro 1 direito' },
	{ label: 'Calo neurovascular em Arteiro 2 direito ', value: 'Calo neurovascular em Arteiro 2 direito' },
	{ label: 'Calo neurovascular em Arteiro 3 direito ', value: 'Calo neurovascular em Arteiro 3 direito' },
	{ label: 'Calo neurovascular em Arteiro 4 direito ', value: 'Calo neurovascular em Arteiro 4 direito' },
	{ label: 'Calo neurovascular em pé esquerdo ', value: 'Calo neurovascular em pé esquerdo' },
	{ label: 'Calo neurovascular em Halux esquerdo ', value: 'Calo neurovascular em Halux esquerdo' },
	{ label: 'Calo neurovascular em Arteiro 1 esquerdo ', value: 'Calo neurovascular em Arteiro 1 esquerdo ' },
	{ label: 'Calo neurovascular em Arteiro 2 esquerdo ', value: 'Calo neurovascular em Arteiro 2 esquerdo ' },
	{ label: 'Calo neurovascular em Arteiro 3 esquerdo ', value: 'Calo neurovascular em Arteiro 3 esquerdo ' },
	{ label: 'Calo neurovascular em Arteiro 4 esquerdo ', value: 'Calo neurovascular em Arteiro 4 esquerdo ' },
];
