export default [
	{ label: 'Bromidrose em Halux direito ', value: 'Bromidrose em Halux direito ' },
	{ label: 'Bromidrose em Arteiro 1 direito ', value: 'Bromidrose em Arteiro 1 direito ' },
	{ label: 'Bromidrose em Arteiro 2 direito ', value: 'Bromidrose em Arteiro 2 direito ' },
	{ label: 'Bromidrose em Arteiro 3 direito ', value: 'Bromidrose em Arteiro 3 direito ' },
	{ label: 'Bromidrose em Arteiro 4 direito ', value: 'Bromidrose em Arteiro 4 direito ' },
	{ label: 'Bromidrose em Halux esquerdo ', value: 'Bromidrose em Halux esquerdo ' },
	{ label: 'Bromidrose em Arteiro 1 esquerdo ', value: 'Bromidrose em Arteiro 1 esquerdo ' },
	{ label: 'Bromidrose em Arteiro 2 esquerdo ', value: 'Bromidrose em Arteiro 2 esquerdo ' },
	{ label: 'Bromidrose em Arteiro 3 esquerdo ', value: 'Bromidrose em Arteiro 3 esquerdo ' },
	{ label: 'Bromidrose em Arteiro 4 esquerdo ', value: 'Bromidrose em Arteiro 4 esquerdo ' },
	{ label: 'Anidrose em Halux direito ', value: 'Anidrose em Halux direito ' },
	{ label: 'Anidrose em Arteiro 1 direito ', value: 'Anidrose em Arteiro 1 direito ' },
	{ label: 'Anidrose em Arteiro 2 direito ', value: 'Anidrose em Arteiro 2 direito ' },
	{ label: 'Anidrose em Arteiro 3 direito ', value: 'Anidrose em Arteiro 3 direito ' },
	{ label: 'Anidrose em Arteiro 4 direito ', value: 'Anidrose em Arteiro 4 direito ' },
	{ label: 'Anidrose em Halux esquerdo ', value: 'Anidrose em Halux esquerdo ' },
	{ label: 'Anidrose em Arteiro 1 esquerdo ', value: 'Anidrose em Arteiro 1 esquerdo ' },
	{ label: 'Anidrose em Arteiro 2 esquerdo ', value: 'Anidrose em Arteiro 2 esquerdo ' },
	{ label: 'Anidrose em Arteiro 3 esquerdo ', value: 'Anidrose em Arteiro 3 esquerdo ' },
	{ label: 'Anidrose em Arteiro 4 esquerdo ', value: 'Anidrose em Arteiro 4 esquerdo ' },
	{ label: 'Hiperhidrose em Halux direito ', value: 'Hiperhidrose em Halux direito ' },
	{ label: 'Hiperhidrose em Arteiro 1 direito ', value: 'Hiperhidrose em Arteiro 1 direito ' },
	{ label: 'Hiperhidrose em Arteiro 2 direito ', value: 'Hiperhidrose em Arteiro 2 direito ' },
	{ label: 'Hiperhidrose em Arteiro 3 direito ', value: 'Hiperhidrose em Arteiro 3 direito ' },
	{ label: 'Hiperhidrose em Arteiro 4 direito ', value: 'Hiperhidrose em Arteiro 4 direito ' },
	{ label: 'Hiperhidrose em Halux esquerdo ', value: 'Hiperhidrose em Halux esquerdo ' },
	{ label: 'Hiperhidrose em Arteiro 1 esquerdo ', value: 'Hiperhidrose em Arteiro 1 esquerdo' },
	{ label: 'Hiperhidrose em Arteiro 2 esquerdo ', value: 'Hiperhidrose em Arteiro 2 esquerdo' },
	{ label: 'Hiperhidrose em Arteiro 3 esquerdo ', value: 'Hiperhidrose em Arteiro 3 esquerdo' },
	{ label: 'Hiperhidrose em Arteiro 4 esquerdo ', value: 'Hiperhidrose em Arteiro 4 esquerdo' },
	{ label: 'Isquemica em Halux direito ', value: 'Isquemica em Halux direito  ' },
	{ label: 'Isquemica em Arteiro 1 direito ', value: 'Isquemica em Arteiro 1 direito' },
	{ label: 'Isquemica em Arteiro 2 direito ', value: 'Isquemica em Arteiro 2 direito' },
	{ label: 'Isquemica em Arteiro 3 direito ', value: 'Isquemica em Arteiro 3 direito' },
	{ label: 'Isquemica em Arteiro 4 direito ', value: 'Isquemica em Arteiro 4 direito' },
	{ label: 'Isquemica em Halux esquerdo ', value: 'Isquemica em Halux esquerdo ' },
	{ label: 'Isquemica em Arteiro 1 esquerdo ', value: 'Isquemica em Arteiro 1 esquerdo ' },
	{ label: 'Isquemica em Arteiro 2 esquerdo ', value: 'Isquemica em Arteiro 2 esquerdo ' },
	{ label: 'Isquemica em Arteiro 3 esquerdo ', value: 'Isquemica em Arteiro 3 esquerdo ' },
	{ label: 'Isquemica em Arteiro 4 esquerdo ', value: 'Isquemica em Arteiro 4 esquerdo ' },
	{ label: 'Tinea Pedis em Halux direito ', value: 'Tinea Pedis em Halux direito ' },
	{ label: 'Tinea Pedis em Arteiro 1 direito ', value: 'Tinea Pedis em Arteiro 1 direito ' },
	{ label: 'Tinea Pedis em Arteiro 2 direito ', value: 'Tinea Pedis em Arteiro 2 direito ' },
	{ label: 'Tinea Pedis em Arteiro 3 direito ', value: 'Tinea Pedis em Arteiro 3 direito ' },
	{ label: 'Tinea Pedis em Arteiro 4 direito ', value: 'Tinea Pedis em Arteiro 4 direito ' },
	{ label: 'Tinea Pedis em Halux esquerdo ', value: 'Tinea Pedis em Halux esquerdo' },
	{ label: 'Tinea Pedis em Arteiro 1 esquerdo ', value: 'Tinea Pedis em Arteiro 1 esquerdo ' },
	{ label: 'Tinea Pedis em Arteiro 2 esquerdo ', value: 'Tinea Pedis em Arteiro 2 esquerdo ' },
	{ label: 'Tinea Pedis em Arteiro 3 esquerdo ', value: 'Tinea Pedis em Arteiro 3 esquerdo ' },
	{ label: 'Tinea Pedis em Arteiro 4 esquerdo ', value: 'Tinea Pedis em Arteiro 4 esquerdo ' },
	{ label: 'Fissuras em Halux direito ', value: 'Fissuras em Halux direito ' },
	{ label: 'Fissuras em Arteiro 1 direito ', value: 'Fissuras em Arteiro 1 direito' },
	{ label: 'Fissuras em Arteiro 2 direito ', value: 'Fissuras em Arteiro 2 direito' },
	{ label: 'Fissuras em Arteiro 3 direito ', value: 'Fissuras em Arteiro 3 direito' },
	{ label: 'Fissuras em Arteiro 4 direito ', value: 'Fissuras em Arteiro 4 direito' },
	{ label: 'Fissuras em Halux esquerdo ', value: 'Fissuras em Halux esquerdo' },
	{ label: 'Fissuras em Arteiro 1 esquerdo ', value: 'Fissuras em Arteiro 1 esquerdo ' },
	{ label: 'Fissuras em Arteiro 2 esquerdo ', value: 'Fissuras em Arteiro 2 esquerdo ' },
	{ label: 'Fissuras em Arteiro 3 esquerdo ', value: 'Fissuras em Arteiro 3 esquerdo ' },
	{ label: 'Fissuras em Arteiro 4 esquerdo ', value: 'Fissuras em Arteiro 4 esquerdo ' },
	{ label: 'Disidrose em Halux direito ', value: 'Disidrose em Halux direito ' },
	{ label: 'Disidrose em Arteiro 1 direito ', value: 'Disidrose em Arteiro 1 direito ' },
	{ label: 'Disidrose em Arteiro 2 direito ', value: 'Disidrose em Arteiro 2 direito ' },
	{ label: 'Disidrose em Arteiro 3 direito ', value: 'Disidrose em Arteiro 3 direito ' },
	{ label: 'Disidrose em Arteiro 4 direito ', value: 'Disidrose em Arteiro 4 direito ' },
	{ label: 'Disidrose em Halux esquerdo ', value: 'Disidrose em Halux esquerdo ' },
	{ label: 'Disidrose em Arteiro 1 esquerdo ', value: 'Disidrose em Arteiro 1 esquerdo ' },
	{ label: 'Disidrose em Arteiro 2 esquerdo ', value: 'Disidrose em Arteiro 2 esquerdo ' },
	{ label: 'Disidrose em Arteiro 3 esquerdo ', value: 'Disidrose em Arteiro 3 esquerdo ' },
	{ label: 'Disidrose em Arteiro 4 esquerdo ', value: 'Disidrose em Arteiro 4 esquerdo ' },
	{ label: 'Mal perfurante em Halux direito ', value: 'Mal perfurante em Halux direito ' },
	{ label: 'Mal perfurante em Arteiro 1 direito ', value: 'Mal perfurante em Arteiro 1 direito ' },
	{ label: 'Mal perfurante em Arteiro 2 direito ', value: 'Mal perfurante em Arteiro 2 direito ' },
	{ label: 'Mal perfurante em Arteiro 3 direito ', value: 'Mal perfurante em Arteiro 3 direito ' },
	{ label: 'Mal perfurante em Arteiro 4 direito ', value: 'Mal perfurante em Arteiro 4 direito ' },
	{ label: 'Mal perfurante em Halux esquerdo ', value: 'Mal perfurante em Halux esquerdo ' },
	{ label: 'Mal perfurante em Arteiro 1 esquerdo ', value: 'Mal perfurante em Arteiro 1 esquerdo ' },
	{ label: 'Mal perfurante em Arteiro 2 esquerdo ', value: 'Mal perfurante em Arteiro 2 esquerdo ' },
	{ label: 'Mal perfurante em Arteiro 3 esquerdo ', value: 'Mal perfurante em Arteiro 3 esquerdo ' },
	{ label: 'Mal perfurante em Arteiro 4 esquerdo ', value: 'Mal perfurante em Arteiro 4 esquerdo ' },
	{ label: 'Psoriase em Halux direito ', value: 'Psoriase em Halux direito ' },
	{ label: 'Psoriase em Arteiro 1 direito ', value: 'Psoriase em Arteiro 1 direito ' },
	{ label: 'Psoriase em Arteiro 2 direito ', value: 'Psoriase em Arteiro 2 direito ' },
	{ label: 'Psoriase em Arteiro 3 direito ', value: 'Psoriase em Arteiro 3 direito ' },
	{ label: 'Psoriase em Arteiro 4 direito ', value: 'Psoriase em Arteiro 4 direito ' },
	{ label: 'Psoriase em Halux esquerdo ', value: 'Psoriase em Halux esquerdo ' },
	{ label: 'Psoriase em Arteiro 1 esquerdo ', value: 'Psoriase em Arteiro 1 esquerdo ' },
	{ label: 'Psoriase em Arteiro 2 esquerdo ', value: 'Psoriase em Arteiro 2 esquerdo ' },
	{ label: 'Psoriase em Arteiro 3 esquerdo ', value: 'Psoriase em Arteiro 3 esquerdo ' },
	{ label: 'Psoriase em Arteiro 4 esquerdo ', value: 'Psoriase em Arteiro 4 esquerdo ' },
];
