export default [
	{ label: 'Onicoatrofia em Halux direito ', value: 'Onicoatrofia em Halux direito ' },
	{ label: 'Onicoatrofia em Arteiro 1 direito ', value: 'Onicoatrofia em Arteiro 1 direito ' },
	{ label: 'Onicoatrofia em Arteiro 2 direito ', value: 'Onicoatrofia em Arteiro 2 direito ' },
	{ label: 'Onicoatrofia em Arteiro 3 direito ', value: 'Onicoatrofia em Arteiro 3 direito ' },
	{ label: 'Onicoatrofia em Arteiro 4 direito ', value: 'Onicoatrofia em Arteiro 4 direito ' },
	{ label: 'Onicoatrofia em Halux esquerdo ', value: 'Onicoatrofia em Halux esquerdo ' },
	{ label: 'Onicoatrofia em Arteiro 1 esquerdo ', value: 'Onicoatrofia em Arteiro 1 esquerdo ' },
	{ label: 'Onicoatrofia em Arteiro 2 esquerdo ', value: 'Onicoatrofia em Arteiro 2 esquerdo ' },
	{ label: 'Onicoatrofia em Arteiro 3 esquerdo ', value: 'Onicoatrofia em Arteiro 3 esquerdo ' },
	{ label: 'Onicoatrofia em Arteiro 4 esquerdo ', value: 'Onicoatrofia em Arteiro 4 esquerdo ' },
	{ label: 'Onicocriptose em Halux direito ', value: 'Onicocriptose em Halux direito ' },
	{ label: 'Onicocriptose em Arteiro 1 direito ', value: 'Onicocriptose em Arteiro 1 direito ' },
	{ label: 'Onicocriptose em Arteiro 2 direito ', value: 'Onicocriptose em Arteiro 2 direito ' },
	{ label: 'Onicocriptose em Arteiro 3 direito ', value: 'Onicocriptose em Arteiro 3 direito ' },
	{ label: 'Onicocriptose em Arteiro 4 direito ', value: 'Onicocriptose em Arteiro 4 direito ' },
	{ label: 'Onicocriptose em Halux esquerdo ', value: 'Onicocriptose em Halux esquerdo ' },
	{ label: 'Onicocriptose em Arteiro 1 esquerdo ', value: 'Onicocriptose em Arteiro 1 esquerdo ' },
	{ label: 'Onicocriptose em Arteiro 2 esquerdo ', value: 'Onicocriptose em Arteiro 2 esquerdo ' },
	{ label: 'Onicocriptose em Arteiro 3 esquerdo ', value: 'Onicocriptose em Arteiro 3 esquerdo ' },
	{ label: 'Onicocriptose em Arteiro 4 esquerdo ', value: 'Onicocriptose em Arteiro 4 esquerdo ' },
	{ label: 'Onicogrifose em Halux direito ', value: 'Onicogrifose em Halux direito ' },
	{ label: 'Onicogrifose em Arteiro 1 direito ', value: 'Onicogrifose em Arteiro 1 direito ' },
	{ label: 'Onicogrifose em Arteiro 2 direito ', value: 'Onicogrifose em Arteiro 2 direito ' },
	{ label: 'Onicogrifose em Arteiro 3 direito ', value: 'Onicogrifose em Arteiro 3 direito ' },
	{ label: 'Onicogrifose em Arteiro 4 direito ', value: 'Onicogrifose em Arteiro 4 direito ' },
	{ label: 'Onicogrifose em Halux esquerdo ', value: 'Onicogrifose em Halux esquerdo ' },
	{ label: 'Onicogrifose em Arteiro 1 esquerdo ', value: 'Onicogrifose em Arteiro 1 esquerdo' },
	{ label: 'Onicogrifose em Arteiro 2 esquerdo ', value: 'Onicogrifose em Arteiro 2 esquerdo' },
	{ label: 'Onicogrifose em Arteiro 3 esquerdo ', value: 'Onicogrifose em Arteiro 3 esquerdo' },
	{ label: 'Onicogrifose em Arteiro 4 esquerdo ', value: 'Onicogrifose em Arteiro 4 esquerdo' },
	{ label: 'Incorrexe em Halux direito ', value: 'Incorrexe em Halux direito  ' },
	{ label: 'Incorrexe em Arteiro 1 direito ', value: 'Incorrexe em Arteiro 1 direito' },
	{ label: 'Incorrexe em Arteiro 2 direito ', value: 'Incorrexe em Arteiro 2 direito' },
	{ label: 'Incorrexe em Arteiro 3 direito ', value: 'Incorrexe em Arteiro 3 direito' },
	{ label: 'Incorrexe em Arteiro 4 direito ', value: 'Incorrexe em Arteiro 4 direito' },
	{ label: 'Incorrexe em Halux esquerdo ', value: 'Incorrexe em Halux esquerdo ' },
	{ label: 'Incorrexe em Arteiro 1 esquerdo ', value: 'Incorrexe em Arteiro 1 esquerdo ' },
	{ label: 'Incorrexe em Arteiro 2 esquerdo ', value: 'Incorrexe em Arteiro 2 esquerdo ' },
	{ label: 'Incorrexe em Arteiro 3 esquerdo ', value: 'Incorrexe em Arteiro 3 esquerdo ' },
	{ label: 'Incorrexe em Arteiro 4 esquerdo ', value: 'Incorrexe em Arteiro 4 esquerdo ' },
	{ label: 'Granulima em Halux direito ', value: 'Granulima em Halux direito ' },
	{ label: 'Granulima em Arteiro 1 direito ', value: 'Granulima em Arteiro 1 direito ' },
	{ label: 'Granulima em Arteiro 2 direito ', value: 'Granulima em Arteiro 2 direito ' },
	{ label: 'Granulima em Arteiro 3 direito ', value: 'Granulima em Arteiro 3 direito ' },
	{ label: 'Granulima em Arteiro 4 direito ', value: 'Granulima em Arteiro 4 direito ' },
	{ label: 'Granulima em Halux esquerdo ', value: 'Granulima em Halux esquerdo' },
	{ label: 'Granulima em Arteiro 1 esquerdo ', value: 'Granulima em Arteiro 1 esquerdo ' },
	{ label: 'Granulima em Arteiro 2 esquerdo ', value: 'Granulima em Arteiro 2 esquerdo ' },
	{ label: 'Granulima em Arteiro 3 esquerdo ', value: 'Granulima em Arteiro 3 esquerdo ' },
	{ label: 'Granulima em Arteiro 4 esquerdo ', value: 'Granulima em Arteiro 4 esquerdo ' },
	{ label: 'Alteração de Cor em Halux direito ', value: 'Alteração de Cor em Halux direito ' },
	{ label: 'Alteração de Cor em Arteiro 1 direito ', value: 'Alteração de Cor em Arteiro 1 direito' },
	{ label: 'Alteração de Cor em Arteiro 2 direito ', value: 'Alteração de Cor em Arteiro 2 direito' },
	{ label: 'Alteração de Cor em Arteiro 3 direito ', value: 'Alteração de Cor em Arteiro 3 direito' },
	{ label: 'Alteração de Cor em Arteiro 4 direito ', value: 'Alteração de Cor em Arteiro 4 direito' },
	{ label: 'Alteração de Cor em Halux esquerdo ', value: 'Alteração de Cor em Halux esquerdo' },
	{ label: 'Alteração de Cor em Arteiro 1 esquerdo ', value: 'Alteração de Cor em Arteiro 1 esquerdo ' },
	{ label: 'Alteração de Cor em Arteiro 2 esquerdo ', value: 'Alteração de Cor em Arteiro 2 esquerdo ' },
	{ label: 'Alteração de Cor em Arteiro 3 esquerdo ', value: 'Alteração de Cor em Arteiro 3 esquerdo ' },
	{ label: 'Alteração de Cor em Arteiro 4 esquerdo ', value: 'Alteração de Cor em Arteiro 4 esquerdo ' },
	{ label: 'Onicolise em Halux direito ', value: 'Onicolise em Halux direito ' },
	{ label: 'Onicolise em Arteiro 1 direito ', value: 'Onicolise em Arteiro 1 direito ' },
	{ label: 'Onicolise em Arteiro 2 direito ', value: 'Onicolise em Arteiro 2 direito ' },
	{ label: 'Onicolise em Arteiro 3 direito ', value: 'Onicolise em Arteiro 3 direito ' },
	{ label: 'Onicolise em Arteiro 4 direito ', value: 'Onicolise em Arteiro 4 direito ' },
	{ label: 'Onicolise em Halux esquerdo ', value: 'Onicolise em Halux esquerdo ' },
	{ label: 'Onicolise em Arteiro 1 esquerdo ', value: 'Onicolise em Arteiro 1 esquerdo ' },
	{ label: 'Onicolise em Arteiro 2 esquerdo ', value: 'Onicolise em Arteiro 2 esquerdo ' },
	{ label: 'Onicolise em Arteiro 3 esquerdo ', value: 'Onicolise em Arteiro 3 esquerdo ' },
	{ label: 'Onicolise em Arteiro 4 esquerdo ', value: 'Onicolise em Arteiro 4 esquerdo ' },
	{ label: 'Onicofose em Halux direito ', value: 'Onicofose em Halux direito ' },
	{ label: 'Onicofose em Arteiro 1 direito ', value: 'Onicofose em Arteiro 1 direito ' },
	{ label: 'Onicofose em Arteiro 2 direito ', value: 'Onicofose em Arteiro 2 direito ' },
	{ label: 'Onicofose em Arteiro 3 direito ', value: 'Onicofose em Arteiro 3 direito ' },
	{ label: 'Onicofose em Arteiro 4 direito ', value: 'Onicofose em Arteiro 4 direito ' },
	{ label: 'Onicofose em Halux esquerdo ', value: 'Onicofose em Halux esquerdo ' },
	{ label: 'Onicofose em Arteiro 1 esquerdo ', value: 'Onicofose em Arteiro 1 esquerdo ' },
	{ label: 'Onicofose em Arteiro 2 esquerdo ', value: 'Onicofose em Arteiro 2 esquerdo ' },
	{ label: 'Onicofose em Arteiro 3 esquerdo ', value: 'Onicofose em Arteiro 3 esquerdo ' },
	{ label: 'Onicofose em Arteiro 4 esquerdo ', value: 'Onicofose em Arteiro 4 esquerdo ' },
	{ label: 'Onicomicose em Halux direito ', value: 'Onicomicose em Halux direito ' },
	{ label: 'Onicomicose em Arteiro 1 direito ', value: 'Onicomicose em Arteiro 1 direito ' },
	{ label: 'Onicomicose em Arteiro 2 direito ', value: 'Onicomicose em Arteiro 2 direito ' },
	{ label: 'Onicomicose em Arteiro 3 direito ', value: 'Onicomicose em Arteiro 3 direito ' },
	{ label: 'Onicomicose em Arteiro 4 direito ', value: 'Onicomicose em Arteiro 4 direito ' },
	{ label: 'Onicomicose em Halux esquerdo ', value: 'Onicomicose em Halux esquerdo ' },
	{ label: 'Onicomicose em Arteiro 1 esquerdo ', value: 'Onicomicose em Arteiro 1 esquerdo ' },
	{ label: 'Onicomicose em Arteiro 2 esquerdo ', value: 'Onicomicose em Arteiro 2 esquerdo ' },
	{ label: 'Onicomicose em Arteiro 3 esquerdo ', value: 'Onicomicose em Arteiro 3 esquerdo ' },
	{ label: 'Onicomicose em Arteiro 4 esquerdo ', value: 'Onicomicose em Arteiro 4 esquerdo ' },
	{ label: 'Exostose Ungueal em Halux direito ', value: 'Exostose Ungueal em Halux direito ' },
	{ label: 'Exostose Ungueal em Arteiro 1 direito ', value: 'Exostose Ungueal em Arteiro 1 direito  ' },
	{ label: 'Exostose Ungueal em Arteiro 2 direito ', value: 'Exostose Ungueal em Arteiro 2 direito  ' },
	{ label: 'Exostose Ungueal em Arteiro 3 direito ', value: 'Exostose Ungueal em Arteiro 3 direito  ' },
	{ label: 'Exostose Ungueal em Arteiro 4 direito ', value: 'Exostose Ungueal em Arteiro 4 direito  ' },
	{ label: 'Exostose Ungueal em Halux esquerdo ', value: 'Exostose Ungueal em Halux esquerdo  ' },
	{ label: 'Exostose Ungueal em Arteiro 1 esquerdo ', value: 'Exostose Ungueal em Arteiro 1 esquerdo ' },
	{ label: 'Exostose Ungueal em Arteiro 2 esquerdo ', value: 'Exostose Ungueal em Arteiro 2 esquerdo ' },
	{ label: 'Exostose Ungueal em Arteiro 3 esquerdo ', value: 'Exostose Ungueal em Arteiro 3 esquerdo ' },
	{ label: 'Exostose Ungueal em Arteiro 4 esquerdo ', value: 'Exostose Ungueal em Arteiro 4 esquerdo ' },
	{ label: 'Psoriase Ungueal em Halux direito ', value: 'Psoriase Ungueal em Halux direito  ' },
	{ label: 'Psoriase Ungueal em Arteiro 1 direito ', value: 'Psoriase Ungueal em Arteiro 1 direito ' },
	{ label: 'Psoriase Ungueal em Arteiro 2 direito ', value: 'Psoriase Ungueal em Arteiro 2 direito ' },
	{ label: 'Psoriase Ungueal em Arteiro 3 direito ', value: 'Psoriase Ungueal em Arteiro 3 direito ' },
	{ label: 'Psoriase Ungueal em Arteiro 4 direito ', value: 'Psoriase Ungueal em Arteiro 4 direito ' },
	{ label: 'Psoriase Ungueal em Halux esquerdo ', value: 'Psoriase Ungueal em Halux esquerdo ' },
	{ label: 'Psoriase Ungueal em Arteiro 1 esquerdo ', value: 'Psoriase Ungueal em Arteiro 1 esquerdo' },
	{ label: 'Psoriase Ungueal em Arteiro 2 esquerdo ', value: 'Psoriase Ungueal em Arteiro 2 esquerdo' },
	{ label: 'Psoriase Ungueal em Arteiro 3 esquerdo ', value: 'Psoriase Ungueal em Arteiro 3 esquerdo' },
	{ label: 'Psoriase Ungueal em Arteiro 4 esquerdo ', value: 'Psoriase Ungueal em Arteiro 4 esquerdo' },
	{ label: 'Onicomadese em Halux direito ', value: 'Onicomadese em Halux direito ' },
	{ label: 'Onicomadese em Arteiro 1 direito ', value: 'Onicomadese em Arteiro 1 direito ' },
	{ label: 'Onicomadese em Arteiro 2 direito ', value: 'Onicomadese em Arteiro 2 direito ' },
	{ label: 'Onicomadese em Arteiro 3 direito ', value: 'Onicomadese em Arteiro 3 direito ' },
	{ label: 'Onicomadese em Arteiro 4 direito ', value: 'Onicomadese em Arteiro 4 direito ' },
	{ label: 'Onicomadese em Halux esquerdo ', value: 'Onicomadese em Halux esquerdo ' },
	{ label: 'Onicomadese em Arteiro 1 esquerdo ', value: 'Onicomadese em Arteiro 1 esquerdo ' },
	{ label: 'Onicomadese em Arteiro 2 esquerdo ', value: 'Onicomadese em Arteiro 2 esquerdo ' },
	{ label: 'Onicomadese em Arteiro 3 esquerdo ', value: 'Onicomadese em Arteiro 3 esquerdo ' },
	{ label: 'Onicomadese em Arteiro 4 esquerdo ', value: 'Onicomadese em Arteiro 4 esquerdo ' },
];
