export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';

export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';

export const SET_USER = 'SET_USER';
export const SET_USERS = 'SET_USERS';
export const LOADING_USER = 'LOADING_USER';

// UI reducer types
export const SET_ERRORS = 'SET_ERRORS';
export const LOADING_UI = 'LOADING_UI';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const LOADING_DATA = 'LOADING_DATA';
export const STOP_LOADING_UI = 'STOP_LOADING_UI';

//Client reducer types
export const FETCH_CLIENT_REQUEST = 'FETCH_CLIENT_REQUEST';
export const FETCH_CLIENT_SUCCESS = 'FETCH_CLIENT_SUCCESS';
export const FETCH_CLIENT_ERROR = 'FETCH_CLIENT_ERROR';
export const FETCH_CLIENTS_REQUEST = 'FETCH_CLIENTS_REQUEST';
export const FETCH_CLIENTS_SUCCESS = 'FETCH_CLIENTS_SUCCESS';
export const FETCH_CLIENTS_ERROR = 'FETCH_CLIENTS_ERROR';

//Consult reducer types
export const SET_CONSULT = 'SET_CONSULT';
export const FETCH_CONSULT_REQUEST = 'FETCH_CONSULT_REQUEST';
export const FETCH_CONSULT_SUCCESS = 'FETCH_CONSULT_SUCCESS';
export const FETCH_CONSULT_ERROR = 'FETCH_CONSULT_ERROR';
export const FETCH_CONSULTS_REQUEST = 'FETCH_CONSULTS_REQUEST';
export const FETCH_CONSULTS_SUCCESS = 'FETCH_CONSULTS_SUCCESS';
export const FETCH_CONSULTS_ERROR = 'FETCH_CONSULTS_ERROR';

//Procedure reducer types
export const FETCH_PROCEDURE_REQUEST = 'FETCH_PROCEDURE_REQUEST';
export const FETCH_PROCEDURE_SUCCESS = 'FETCH_PROCEDURE_SUCCESS';
export const FETCH_PROCEDURE_ERROR = 'FETCH_PROCEDURE_ERROR';
export const FETCH_PROCEDURES_REQUEST = 'FETCH_PROCEDURES_REQUEST';
export const FETCH_PROCEDURES_SUCCESS = 'FETCH_PROCEDURES_SUCCESS';
export const FETCH_PROCEDURES_ERROR = 'FETCH_PROCEDURES_ERROR';

//Service reducer types
export const FETCH_SERVICE_REQUEST = 'FETCH_SERVICE_REQUEST';
export const FETCH_SERVICE_SUCCESS = 'FETCH_SERVICE_SUCCESS';
export const FETCH_SERVICE_ERROR = 'FETCH_SERVICE_ERROR';
export const FETCH_SERVICES_REQUEST = 'FETCH_SERVICES_REQUEST';
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS';
export const FETCH_SERVICES_ERROR = 'FETCH_SERVICES_ERROR';
